version: '3.9'

services:
  frontend:
    build:
      context: /tmp/myapp/hsfuldablog/frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: /tmp/myapp/hsfuldablog/backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://admin:fbftuKPSZwNfv4a2@messageboard-database.mjot3.mongodb.net/messageboard?retryWrites=true&ssl=true
    restart: unless-stopped
    network_mode: "host"

  backup:
    build:
      context: /tmp/myapp/hsfuldablog/backup
      dockerfile: Dockerfile.backup
    environment:
      - MONGO_URI=mongodb+srv://admin:fbftuKPSZwNfv4a2@messageboard-database.mjot3.mongodb.net/messageboard?retryWrites=true&ssl=true
    volumes:
      - backup_data:/backup
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backup_data:
