version: '3.9'

services:
  frontend:
    build:
      context: /tmp/myapp/hsfuldablog/frontend
      # Adjusted path since we're in hsfuldablog directory
      # Expose the frontend to the host on port 8080
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: /tmp/myapp/hsfuldablog/backend
      # Adjusted path since we're in hsfuldablog directory
      # Expose backend on port 5000 for debugging
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://admin:fbftuKPSZwNfv4a2@messageboard-database.mjot3.mongodb.net/messageboard?retryWrites=true&ssl=true
    restart: unless-stopped
    network_mode: "host"

networks:
  app-network:
    driver: bridge